### ISSUE TITLE
References to "Software"

### ISSUE THREAD

**Issue by alvieboy** [non-ai-licenses/non-ai-licenses#1]
Some of the listed BSD licenses are used outside of the software world (for example, HDL designs), however your modifications to the licenses explicitly state that the AI clause applies to "Software", which may not apply ton non-software or mixed projects. 
This might apply to non-BSD licenses as well.
I suggest replacing "Software" with a broader term so that these licenses can be used in non-software or mixed-software projects.

**Comment by alvieboy** [comment]
If the license already mentions "Software" I would stick to the terminology. For other licenses I think you will need to change them on a per-license basis.
For BSD licenses, I think "source code" would be the better solution, since the term is already used across the license, and I suspect there will be no use cases for AI training with binary data (but you can prove me wrong).

**Comment by axel22** [comment]
Here are a few PRs to address this:

https://github.com/non-ai-licenses/non-ai-licenses/pull/2
https://github.com/non-ai-licenses/non-ai-licenses/pull/3
https://github.com/non-ai-licenses/non-ai-licenses/pull/4

**Comment by axel22** [comment]
Also: https://github.com/non-ai-licenses/non-ai-licenses/pull/5

**Comment by axel22** [comment]
Should be fixed now, closing this issue.
