### ISSUE TITLE
The legality of these licenses

### ISSUE THREAD

**Issue by alexlnkp** [non-ai-licenses/non-ai-licenses#14]
Frankly, I'm not a legal expert nor am I competent enough to be one. What I'm wondering is if those licenses have any **ACTUAL** weight legally. There aren't any laws on stealing data to train AI, so I'm not sure if the licenses can even do anything about that. Especially since AIs and the companies behind them never disclose what data they train their plagiarism machines on.
Any experts and knowledgeable people here who can enlighten me about this?

**Comment by zefr0x** [comment]
Also, not an expert, but **`stealing`** is not the right word here.

**Comment by aral-matrix** [comment]
I am actually very much in favor of licenses like this - and found the repo explicitly looking for such licenses with restrictions for "AI" training data. I just wonder if maybe the repository should be hosted with a provider that has the same attitude to not train AI on open source - e.g. codeberg.org

I am not a lawyer but I believe I do not need to be to conclude: the question is not whether these licenses have any legal weight (they absolutely do), but whether or not they can be enforced (chances are they can not).

Things being as they are, "why bother?" you may ask. And I will use and advocate such licenses from now on, to make a statement AND to set the legal foundation for potential future anti-trust lawsuits.

Chances are very low, but not zero, that at some point in the future, some company will be held accountable for mass violations of copyrights. And in that case, they may argue that using open source as training data was "fair use". That argument falls flat if they are found in breach of licenses that explicitly forbid the use of sources as training data.

**Comment by alexlnkp** [comment]
> I am actually very much in favor of licenses like this - and found the repo explicitly looking for such licenses with restrictions for "AI" training data. I just wonder if maybe the repository should be hosted with a provider that has the same attitude to not train AI on open source - e.g. codeberg.org
> 
> I am not a lawyer but I believe I do not need to be to conclude: the question is not whether these licenses have any legal weight (they absolutely do), but whether or not they can be enforced (chances are they can not).
> 
> Things being as they are, "why bother?" you may ask. And my answer is: I will use and advocate such licenses from now on, to make a statement AND to set the legal foundation for potential future anti-trust lawsuits.
> 
> Chances are very low, but not zero, that at some point in the future, some company will be held accountable for mass violations of copyrights. And in that case, they may argue that using open source as training data was "fair use". That argument falls flat if they are found in breach of licenses that explicitly forbid the use of sources as training data.

Thank You for your answer! I agree with the idea of doing this for the future, but unfortunately as it stands even now, it's extremely difficult to prove your code was used to train AI, as it simply mishmashes a bunch of snippets together, creating something **_technically_** """unique""". Even if AI companies are forced to disclose the training data (which is unfortunately unlikely), I don't believe there will be enough repercussions for scraping content off the internet, even if they breach the licenses of said content.
Speaking of, if the license is breached, that means someone has to sue, right? If so, who has to sue, the author of the content or the repo hosting website? If it's the former, then I'm not sure it's viable to go against a gigantic multi-million/billion dollar company for an individual, even if they're in the right (or at least the internet taught me as much).
Still, I switched licenses for all of my projects for the NON-AI versions of them, even made one for the "Unlicense" license, as a way of contributing to the cause.

ONCE AGAIN I'M NOT A LEGAL EXPERT, I DON'T KNOW WHAT I'M TALKING ABOUT AND I'M SIMPLY LISTING MY CONCERNS; PLEASE CORRECT ME IF I WAS WRONG IN ANY OF THINGS I LISTED AND THOUGHT OF AS BEING A POSSIBILITY.

**Comment by aral-matrix** [comment]
As I was saying:
> to set the legal foundation for potential future anti-trust lawsuits.

That means there would be millions of copyright violations entering such a lawsuit as a statistic, and as an individual author, you do not have to do anything (except maybe a few of us would be asked as witnesses to a court proceeding).

**Comment by alexlnkp** [comment]
> As I was saying:
> 
> > to set the legal foundation for potential future anti-trust lawsuits.
> 
> That means there would be millions of copyright violations entering such a lawsuit as a statistic, and as an individual author, you do not have to do anything (except maybe a few of us would be asked as witnesses to a court proceeding).

Alrighty, I think I understand now.
Thank You so much for this answer! :)

Closing this issue now
