### ISSUE TITLE
Are these licences addons or standalone?

### ISSUE THREAD

**Issue by CristianKerr** [non-ai-licenses/non-ai-licenses#8]
Hi, 
sorry I am way too new to this, but how would I use one of these licenses?
Do I have to also attach the original license with the noAI one? Or attaching one of these noAI licenses to a project automatically includes the original ones?
Thank you.

**Comment by wolterhv** [comment]
Hi Christian, no need to attach the original license, in fact it would be ambiguous. Just attach the no AI license of your choice; these licenses are standalone.

**Comment by axel22** [comment]
Exactly, the intent is that you only use the license file from this repository, which is a derivation of the respective original license.
